_name_or_path:
    value: klue/roberta-large
_wandb:
    value:
        cli_version: 0.21.0
        e:
            8d1dx773viinm7gccxy30ihqclqp3nj0:
                args:
                    - --model_name
                    - klue/roberta-large
                codePath: code/_ann.py
                codePathLocal: _ann.py
                cpu_count: 56
                cpu_count_logical: 112
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "540911566848"
                        used: "10424078336"
                email: singfor7012@gmail.com
                executable: /home1/aiphw227/miniconda3/envs/bert/bin/python3.11
                git:
                    commit: 48f8bb9ac5ed3e5a706a049db97649367814a406
                    remote: https://github.com/funny-rl/dacon_llm_detection.git
                gpu: NVIDIA RTX A6000
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-e9212e5c-ff26-2801-7cb4-680f5938c976
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-3e0a5176-66b3-de0b-ec07-6d7c3ebdb422
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-1ae5bb89-5124-c08b-a136-e359d8e274e4
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-024c9f3b-3802-0e79-a89c-ea2b900fa41c
                host: n093.hpc
                memory:
                    total: "1081823133696"
                os: Linux-4.18.0-553.5.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /gpfs/home1/aiphw227/llm_detection/dacon_llm_detection/code/_ann.py
                python: CPython 3.11.13
                root: /gpfs/home1/aiphw227/llm_detection/dacon_llm_detection/code
                slurm:
                    cluster_name: cluster
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00000000000000000000000FFFFF
                    cpu_bind_list: "0x00000000000000000000000FFFFF"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "20"
                    cpus_per_task: "20"
                    gpus_on_node: "4"
                    gtids: "0"
                    job_account: uos
                    job_cpus_per_node: "20"
                    job_end_time: "1752639363"
                    job_gid: "100"
                    job_group: users
                    job_id: "445116"
                    job_name: bash
                    job_nodelist: n093
                    job_num_nodes: "1"
                    job_partition: gpu4
                    job_qos: max_10
                    job_start_time: "1752466563"
                    job_uid: "1291"
                    job_user: aiphw227
                    jobid: "445116"
                    launch_node_ipaddr: 192.168.140.2
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: n093
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "36395"
                    pty_win_col: "111"
                    pty_win_row: "35"
                    srun_comm_host: 192.168.140.2
                    srun_comm_port: "37585"
                    step_gpus: 0,1,2,3
                    step_id: "0"
                    step_launcher_port: "37585"
                    step_nodelist: n093
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /gpfs/home1/aiphw227
                    submit_host: gate1.hpc
                    task_pid: "18459"
                    tasks_per_node: "1"
                    topology_addr: n093
                    topology_addr_pattern: node
                    tres_per_task: cpu:20
                    umask: "0022"
                startedAt: "2025-07-14T10:24:03.145768Z"
                writerId: 8d1dx773viinm7gccxy30ihqclqp3nj0
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 100
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 100
            "3":
                - 7
                - 13
                - 19
                - 66
            "4": 3.11.13
            "5": 0.21.0
            "6": 4.53.1
            "9":
                "1": transformers_trainer
            "12": 0.21.0
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - RobertaForMaskedLM
attention_probs_dropout_prob:
    value: 0.1
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: false
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: 0
chunk_size_feed_forward:
    value: 0
classifier_dropout:
    value: null
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: true
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 2
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 250
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: true
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: true
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: gelu
hidden_dropout_prob:
    value: 0.1
hidden_size:
    value: 1024
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": 0
        "1": 1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 4096
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        "0": 0
        "1": 1
layer_norm_eps:
    value: 1e-05
learning_rate:
    value: 2e-05
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: ./ann_models/klue/roberta-large/runs/Jul14_19-23-57_n093.hpc
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 50
logging_strategy:
    value: steps
lr_scheduler_type:
    value: constant
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 514
max_steps:
    value: -1
metric_for_best_model:
    value: eval_auroc
min_length:
    value: 0
model/num_parameters:
    value: 336658434
model_type:
    value: roberta
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 16
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 24
num_return_sequences:
    value: 1
num_train_epochs:
    value: 5
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ./ann_models/klue/roberta-large
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: 1
past_index:
    value: -1
per_device_eval_batch_size:
    value: 32
per_device_train_batch_size:
    value: 32
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
position_embedding_type:
    value: absolute
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
run_name:
    value: ./ann_models/klue/roberta-large
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 250
save_strategy:
    value: steps
save_total_limit:
    value: 1
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: BertTokenizer
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: float32
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
transformers_version:
    value: 4.53.1
type_vocab_size:
    value: 1
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
vocab_size:
    value: 32000
warmup_ratio:
    value: 0
warmup_steps:
    value: 250
weight_decay:
    value: 0
